#permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

paginate: 3

# Only First Paragraph plugin
only_first_p:
  show_read_more_link: true
  read_more_link_text: 'Read more'
